import 'dart:convert';

import 'package:drift/drift.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../db/database_provider.dart';
import '../db/schema/app_database.dart';
import '../network/supabase_client.dart';
import 'sync_engine.dart';
import 'sync_status.dart';

/// Provider del motor de sincronización (null si supabase no está configurado).
final syncEngineProvider = Provider<SyncEngine?>((ref) {
  final client = ref.watch(supabaseProvider);
  if (client == null) return null;
  final db = ref.watch(appDatabaseProvider);
  final engine = SyncEngine(db: db, client: client);
  // Progreso: logs (vía LogBridge) + barra global de sync.
  engine.onProgress = (msg) {
    print('[sync] $msg');
    ref.read(syncStatusProvider.notifier).progreso(SyncOrigen.general, msg);
  };
  // Errores fatales: muestran el detalle completo en la barra para poder
  // copiarlo desde el diálogo.
  engine.onSyncError = (detalle) {
    ref
        .read(syncStatusProvider.notifier)
        .error(SyncOrigen.general, 'Error en la sincronización',
            detalle: detalle);
  };
  return engine;
});

/// Estado offline del SyncEngine (indicador de conexión global en el header).
final isOfflineProvider = Provider<bool>((ref) {
  final sync = ref.watch(syncEngineProvider);
  return sync?.isOffline == true;
});

/// Serializa un `Producto` para la cola de sync.
///
/// Se conserva el `id` local: el server usa `id SERIAL` (generated by default),
/// que acepta ids explícitos, y así las referencias de hijos (movimientos,
/// existencias) apuntan al mismo id en local y en remoto.
Map<String, dynamic> productoToSyncMap(Producto p) => {
      'id': p.id,
      'nombre': p.nombre,
      'codigo': p.codigo,
      'descripcion': p.descripcion,
      'categoria_id': p.categoriaId,
      'es_pesable': p.esPesable == 1,
      'requiere_foto_peso': p.requiereFotoPeso == 1,
      'peso_unitario': p.pesoUnitario ?? 0,
      'precio_venta': p.precioVenta,
      'unidad_medida': p.unidadMedida,
      'stock_actual': p.stockActual,
      'stock_minimo': p.stockMinimo,
      'activo': p.activo == 1,
      'tipo': p.tipo,
      'almacen_predeterminado': p.almacenPredeterminado,
      'updated_at':
          p.updatedAt?.toUtc().toIso8601String() ?? DateTime.now().toUtc().toIso8601String(),
    };

/// Serializa un `Proveedore` para la cola de sync (con su id local).
Map<String, dynamic> proveedorToSyncMap(Proveedore p) => {
      'id': p.id,
      'nombre': p.nombre,
      'rif': p.rif,
      'telefono': p.telefono,
      'email': p.email,
      'direccion': p.direccion,
      'contacto': p.contacto,
      'observaciones': p.observaciones,
      'estado': p.estado,
      'created_at': p.createdAt?.toUtc().toIso8601String(),
    };

/// Serializa una `Categoria` para la cola de sync (con su id local).
Map<String, dynamic> categoriaToSyncMap(Categoria c) => {
      'id': c.id,
      'nombre': c.nombre,
      'descripcion': c.descripcion,
      'imagen': c.imagen,
      'color': c.color,
      'activo': c.activo == 1,
      'visible_en_pos': c.visibleEnPos == 1,
      'created_at': c.createdAt?.toUtc().toIso8601String(),
      'updated_at':
          c.updatedAt?.toUtc().toIso8601String() ?? DateTime.now().toUtc().toIso8601String(),
    };

/// Registra una operación pendiente en la cola de sync (outbox).
/// Réplica de `SyncQueue.add_pending()` de sync_queue.py.
Future<int> addPending(
  AppDatabase db, {
  required String tableName,
  required String operation,
  required Map<String, dynamic> data,
}) async {
  return db.into(db.syncQueue).insert(
        SyncQueueCompanion.insert(
          targetTable: tableName,
          operation: operation,
          data: jsonEncode(data),
          createdAt: DateTime.now(),
          status: const Value('pending'),
        ),
      );
}