/// Paleta portada y extendida de `usr/theme.py`.
///
/// Tema oscuro: base violeta profundo (casi negro), superficies moradas,
/// acento púrpura `#BB86FC` y complementarios:
///   - `tertiary`: fucsia/rosa (complemento armónico del morado)
///   - `info`: cian   | `success`: verde menta | `warning`: ámbar | `error`: coral
class AppColors {
  /// Tema oscuro (morados/púrpuras).
  static const dark = <String, String>{
    'bg': '#0B0714',
    'surface': '#13101F',
    'surface_variant': '#221B38',
    'card': '#1A1530',
    'card_hover': '#241D3D',
    'border': '#2F2748',
    'text_primary': '#F4F0FF',
    'text_secondary': '#CBBDEB',
    'text_hint': '#8F85AD',
    'accent': '#BB86FC',
    'accent_dark': '#8B5CF6',
    'accent_container': '#3B2E63',
    'on_accent_container': '#E5D9FF',
    'tertiary': '#FF80AB',
    'nav_bg': '#0A0612',
    'input_bg': '#181228',
    'input_border': '#3B3163',
    'input_text': '#F4F0FF',
    'input_hint': '#8F85AD',
    'primary': '#BB86FC',
    'success': '#6FCF97',
    'warning': '#FFB74D',
    'error': '#FF6B6B',
    'info': '#4DD0E1',
    'white': '#FFFFFF',
    'black': '#000000',
    'header_bg': '#150D2B',
    'header_bg_2': '#0A0612',
    'header_title': '#FFFFFF',
    'header_subtitle': '#CBBDEB',
    'header_icon': '#D0B6FF',
    'drawer_bg': '#0A0612',
    'drawer_active_bg': '#4B2E8F',
    'drawer_active_fg': '#FFFFFF',
    'drawer_inactive_fg': '#C7BFD9',
    'drawer_on_surface': '#EDE8FF',
    'more_surface': '#181228',
    'blue_50': '#0F2A3D',
    'green_50': '#13301E',
    'orange_50': '#47351D',
    'red_50': '#3B1B22',
  };

  /// Tema claro (lavanda suave, acento violeta).
  static const light = <String, String>{
    'bg': '#F5F2FB',
    'surface': '#EFEAF8',
    'surface_variant': '#E3DAF4',
    'card': '#FFFFFF',
    'card_hover': '#ECE5F9',
    'border': '#D8CDEC',
    'text_primary': '#1B1233',
    'text_secondary': '#4B4464',
    'text_hint': '#7E7699',
    'accent': '#7C4DFF',
    'accent_dark': '#5B3FD4',
    'accent_container': '#E9DFFF',
    'on_accent_container': '#2A0A6B',
    'tertiary': '#D63384',
    'nav_bg': '#FFFFFF',
    'input_bg': '#FFFFFF',
    'input_border': '#BFAEE4',
    'input_text': '#1B1233',
    'input_hint': '#7E7699',
    'primary': '#7C4DFF',
    'success': '#2E7D32',
    'warning': '#F57C00',
    'error': '#D32F2F',
    'info': '#0288D1',
    'white': '#FFFFFF',
    'black': '#000000',
    'header_bg': '#3B1E85',
    'header_bg_2': '#2A0F66',
    'header_title': '#FFFFFF',
    'header_subtitle': '#D6C9F5',
    'header_icon': '#E0CFFF',
    'drawer_bg': '#FFFFFF',
    'drawer_active_bg': '#EAE1FF',
    'drawer_active_fg': '#2A0A6B',
    'drawer_inactive_fg': '#494454',
    'drawer_on_surface': '#1A1A1C',
    'more_surface': '#FFFFFF',
    'blue_50': '#CDE8FD',
    'green_50': '#E8F5E9',
    'orange_50': '#FFF3E0',
    'red_50': '#FBE9E7',
  };

  static Map<String, String> of(bool isDark) => isDark ? dark : light;
}
